SET SERVEROUTPUT ON;
BEGIN
    FOR v_counter IN 1 .. 10 LOOP
        DBMS_OUTPUT.PUT_LINE(v_counter);
    END LOOP;
END;
/

SET SERVEROUTPUT ON;
BEGIN
    FOR v_counter IN REVERSE 1 .. 10 LOOP
        DBMS_OUTPUT.PUT_LINE(v_counter);
    END LOOP;
END;
/

